---
- hosts: all
  ignore_errors: yes
  become: yes
  tasks:

   - name: update server
     yum:
      name: "*"
      state: latest
     when: ansible_distribution == "CentOS"

   - name: update tree
     apt:
      name: "*"
      state: latest
     when: ansible_distribution == "Ubuntu"
